# Data Manipulation with Pandas

We've been looking at NumPy and its `ndarray` object

- This provides efficient storage and manipulation of dense typed arrays

Pandas is built on NumPy and provides an efficient implementation of a `DataFrame`

- Convenient storage interface for labelled data.

- Provides powerful data operations familiar to users of database and spreadsheet programs.

NumPy useful for providing essential features for data organization.

It is however limited where flexibility is required:

- attaching labels to data

- working with missing data

- attempting operations that do not map well to element-wise broadcasting e.g grouping

Pandas helps in these "data munging tasks" that occupy much of a data scientist's time.

In [1]:
!pip install pandas

Requirement already satisfied: pandas in /opt/homebrew/anaconda3/lib/python3.12/site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /opt/homebrew/anaconda3/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
# Importing pandas and numpy
import pandas as pd
import numpy as np

## 1. Basic Data Structures

The main data structures of Pandas are `Series` and `DataFrame`, where data are stored and manipulated. 

A `Series` is simply a column (or row) of a database and a `DataFrame` is a database table that includes multiple `Series`.

### 1.1 Series Object

To construct a `Series` we use the function `pd.Series(data, index)`.

The input `data` parameter can take various different forms, the most common of which are:

- `data` as a list or 1-D array of entries, with another array `index` labelling each entry
- `data` as a dictionary containing both entries and labels, with `index` not used

Either way, we end up with the same form of the `Series`, which can now be indexed using the labels.

Let's see an example of a student's final exam score for four modules:

In [3]:
# input data as a list
final_exam_score = pd.Series(data = [82, 80, 93, 32],
                             index = ['Math', 'Machine Learning', 'Financial Statistics', 'Python'])
final_exam_score

Math                    82
Machine Learning        80
Financial Statistics    93
Python                  32
dtype: int64

In [4]:
# input data as a dictionary
final_exam_score = pd.Series(data = {'Math': 82, 'Machine Learning': 80, 
                                     'Financial Statistics': 93, 'Python': 32})
final_exam_score

Math                    82
Machine Learning        80
Financial Statistics    93
Python                  32
dtype: int64

To obtain the value of interest:

In [5]:
# Math score
math_score = final_exam_score['Math']
math_score

82

To modify the value of interest:

In [6]:
final_exam_score['Python'] = 95
final_exam_score

Math                    82
Machine Learning        80
Financial Statistics    93
Python                  95
dtype: int64

To slice a set of wanted values:

In [7]:
wanted_subjects = ['Machine Learning', 'Financial Statistics']
wanted_scores = final_exam_score[wanted_subjects]
wanted_scores

Machine Learning        80
Financial Statistics    93
dtype: int64

#### Quiz

Let's assume if we have a set of population data for several countries:

        China      1,416,096,094	
        UK            69,551,332
        USA          347,275,807
        Singapore      5,870,750

Please try to:

1. Construct a `Series` object that include the population data shown above.

In [8]:
population = pd.Series(data = [1416096094, 69551332, 347275807, 5870750], index = ["China", "UK", "USA", "Singapore"])
population

China        1416096094
UK             69551332
USA           347275807
Singapore       5870750
dtype: int64

# DELETE

2. The population for UK and Singapore is incorrectly swapped! Let's swap it back.

In [9]:
UK_population = population["Singapore"]
population["Singapore"] = population["UK"]
population["UK"] = UK_population
population

China        1416096094
UK              5870750
USA           347275807
Singapore      69551332
dtype: int64

### 1.2 DataFrame Object

Like the `Series` object discussed in the previous section, the `DataFrame` can be thought of either as a n-Dimensional NumPy array, or as an array of dictionaries.

Following the example of the student's scores, we may want to have an overview breakdowns for all components, including mid-term exam and project scores that may affect the student's final score. A `DataFrame` is a good option to form all the scores in a spreadsheet.

In [10]:
midterm_scores = pd.Series(data = {'Math': 90, 'Machine Learning': 70, 
                                   'Financial Statistics': 88, 'Python': 75})
project_scores = pd.Series(data = {'Math': 75, 'Machine Learning': 85, 
                                   'Financial Statistics': 80, 'Python': 90})

# Create a DataFrame, with column names as keys
scores_overview = pd.DataFrame({'Final': final_exam_score,
                                'Midterm': midterm_scores, 
                                'Project': project_scores})
scores_overview

                      Final  Midterm  Project
Math                     82       90       75
Machine Learning         80       70       85
Financial Statistics     93       88       80
Python                   95       75       90

let's check the index labels:

In [11]:
scores_overview.index

Index(['Math', 'Machine Learning', 'Financial Statistics', 'Python'], dtype='object')

`DataFrame` also have columns attribute:

In [12]:
scores_overview.columns

Index(['Final', 'Midterm', 'Project'], dtype='object')

#### 1.2.1 Indexing and Slicing:
 
To slice the `Project` column as a `Series`:

By refering to the corresponding `DataFrame` attribute:

In [13]:
scores_overview.Project

Math                    75
Machine Learning        85
Financial Statistics    80
Python                  90
Name: Project, dtype: int64

Or by simple indexing (but not recommended in current version of `Pandas`)

In [14]:
scores_overview['Project']

Math                    75
Machine Learning        85
Financial Statistics    80
Python                  90
Name: Project, dtype: int64

Or by `.loc` property (label-location and explicit indexing):

In [15]:
scores_overview.loc[:,'Project']# recommended in the last version

Math                    75
Machine Learning        85
Financial Statistics    80
Python                  90
Name: Project, dtype: int64

Or by `.iloc` property (integer-location, and implicit indexing):

In [16]:
scores_overview.iloc[:,2]

Math                    75
Machine Learning        85
Financial Statistics    80
Python                  90
Name: Project, dtype: int64

#### Quiz

1. Can you try to access to the project score for Machine Learning?

In [17]:
scores_overview.loc["Machine Learning", "Project"]

85

2. Can you try to slice the mid-term and final scores for financial statistics module?

In [18]:
scores_overview.iloc[2, [1, 0]]

Midterm    88
Final      93
Name: Financial Statistics, dtype: int64

#### 1.2.2 Simple calculations

If we know that the overall score is a weighted sum of the three components, where the weights are:
- Final: 0.6
- Midterm: 0.3
- Project: 0.1

And we want to add a new column named "module score" to calculate the weighted sum:

In [19]:
overall_score = 0.6*scores_overview["Final"] + 0.3*scores_overview["Midterm"] + 0.1*scores_overview["Project"]
scores_overview["overall"] = overall_score
scores_overview

                      Final  Midterm  Project  overall
Math                     82       90       75     83.7
Machine Learning         80       70       85     77.5
Financial Statistics     93       88       80     90.2
Python                   95       75       90     88.5

In [20]:
overall_score = 0.6*scores_overview["Final"] + 0.3*scores_overview["Midterm"] + 0.1*scores_overview["Project"]
overall_score

Math                    83.7
Machine Learning        77.5
Financial Statistics    90.2
Python                  88.5
dtype: float64

And then, we want to add a new row to calculate the average score for every components over all modules:

In [21]:
scores_overview.loc['Average'] = scores_overview.mean(axis = 0) #columns
scores_overview

                      Final  Midterm  Project  overall
Math                   82.0    90.00     75.0   83.700
Machine Learning       80.0    70.00     85.0   77.500
Financial Statistics   93.0    88.00     80.0   90.200
Python                 95.0    75.00     90.0   88.500
Average                87.5    80.75     82.5   84.975

#### Quiz

1. What will happen if we set `axis = 1`?

In [22]:
scores_overview.mean(axis = 1)

Math                    82.67500
Machine Learning        78.12500
Financial Statistics    87.80000
Python                  87.12500
Average                 83.93125
dtype: float64

In [23]:
scores_overview.loc[:,'Average'] = scores_overview.mean(axis = 1)
scores_overview

                      Final  Midterm  Project  overall   Average
Math                   82.0    90.00     75.0   83.700  82.67500
Machine Learning       80.0    70.00     85.0   77.500  78.12500
Financial Statistics   93.0    88.00     80.0   90.200  87.80000
Python                 95.0    75.00     90.0   88.500  87.12500
Average                87.5    80.75     82.5   84.975  83.93125

#### 1.2.3 Column/Row drop

To drop the row of computed Average:

In [24]:
scores_overview.drop('Average', axis = 1, inplace = True) #save change
scores_overview

                      Final  Midterm  Project  overall
Math                   82.0    90.00     75.0   83.700
Machine Learning       80.0    70.00     85.0   77.500
Financial Statistics   93.0    88.00     80.0   90.200
Python                 95.0    75.00     90.0   88.500
Average                87.5    80.75     82.5   84.975

#### Quiz

1. What will happen if we set `inplace = False`? Try to drop the column of Overall.

## 2. Data Loading and Viewing

Pandas supports loading, reading, and writing data from/to various file formats, including CSV, Excel, JSON, SQL, etc. by converting it to a DataFrame. Meanwhile, Pandas provides some basic tools to view the data and their derivatives.

### 2.1 Data Loading

Let's try to load "The California Housing Dataset" from scikit-learn. We set the parameter `as_Frame` to `True` so that the data will come in the form of a Pandas dataframe already

##### Boston Housing Dataset

In [25]:
from sklearn.datasets import fetch_california_housing
california_housing = fetch_california_housing(as_frame=True)
print(california_housing.DESCR)

.. _california_housing_dataset:

California Housing dataset
--------------------------

**Data Set Characteristics:**

:Number of Instances: 20640

:Number of Attributes: 8 numeric, predictive attributes and the target

:Attribute Information:
    - MedInc        median income in block group
    - HouseAge      median house age in block group
    - AveRooms      average number of rooms per household
    - AveBedrms     average number of bedrooms per household
    - Population    block group population
    - AveOccup      average number of household members
    - Latitude      block group latitude
    - Longitude     block group longitude

:Missing Attribute Values: None

This dataset was obtained from the StatLib repository.
https://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html

The target variable is the median house value for California districts,
expressed in hundreds of thousands of dollars ($100,000).

This dataset was derived from the 1990 U.S. census, using one row per census
block group. A block group is the smallest geographical unit for which the U.S.
Census Bureau publishes sample data (a block group typically has a population
of 600 to 3,000 people).

A household is a group of people residing within a home. Since the average
number of rooms and bedrooms in this dataset are provided per household, these
columns may take surprisingly large values for block groups with few households
and many empty houses, such as vacation resorts.

It can be downloaded/loaded using the
:func:`sklearn.datasets.fetch_california_housing` function.

.. rubric:: References

- Pace, R. Kelley and Ronald Barry, Sparse Spatial Autoregressions,
  Statistics and Probability Letters, 33 (1997) 291-297

Now let's get the dataframe from the dataset

In [26]:
df = california_housing.frame
df

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422
...,...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09,0.781
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21,0.771
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22,0.923
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32,0.847
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24,0.894

### 2.2 Data Viewing and Data Derivatives

#### 2.2.1 Viewing Data

To view first or last few rows of the `DataFrame`:

In [27]:
# First 5 rows
df.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422

In [28]:
# Last 2 rows
df.tail(2)

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32,0.847
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24,0.894

#### 2.2.2 Data Derivatives

To transpose the `DataFrame`:

In [29]:
dftranspose = df.T
dftranspose

,0,1,2,3,4,5,6,7,8,9,...,20630,20631,20632,20633,20634,20635,20636,20637,20638,20639
MedInc,8.325200,8.301400,7.257400,5.643100,3.846200,4.036800,3.659100,3.120000,2.080400,3.691200,...,3.567300,3.517900,3.125000,2.549500,3.712500,1.560300,2.556800,1.700000,1.867200,2.388600
HouseAge,41.000000,21.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,42.000000,52.000000,...,11.000000,15.000000,15.000000,27.000000,28.000000,25.000000,18.000000,17.000000,18.000000,16.000000
AveRooms,6.984127,6.238137,8.288136,5.817352,6.281853,4.761658,4.931907,4.797527,4.294118,4.970588,...,5.932584,6.145833,6.023377,5.445026,6.779070,5.045455,6.114035,5.205543,5.329513,5.254717
AveBedrms,1.023810,0.971880,1.073446,1.073059,1.081081,1.103627,0.951362,1.061824,1.117647,0.990196,...,1.134831,1.141204,1.080519,1.078534,1.148256,1.133333,1.315789,1.120092,1.171920,1.162264
Population,322.000000,2401.000000,496.000000,558.000000,565.000000,413.000000,1094.000000,1157.000000,1206.000000,1551.000000,...,1257.000000,1200.000000,1047.000000,1082.000000,1041.000000,845.000000,356.000000,1007.000000,741.000000,1387.000000
AveOccup,2.555556,2.109842,2.802260,2.547945,2.181467,2.139896,2.128405,1.788253,2.026891,2.172269,...,2.824719,2.777778,2.719481,2.832461,3.026163,2.560606,3.122807,2.325635,2.123209,2.616981
Latitude,37.880000,37.860000,37.850000,37.850000,37.850000,37.850000,37.840000,37.840000,37.840000,37.840000,...,39.290000,39.330000,39.260000,39.190000,39.270000,39.480000,39.490000,39.430000,39.430000,39.370000
Longitude,-122.230000,-122.220000,-122.240000,-122.250000,-122.250000,-122.250000,-122.250000,-122.250000,-122.260000,-122.250000,...,-121.320000,-121.400000,-121.450000,-121.530000,-121.560000,-121.090000,-121.210000,-121.220000,-121.320000,-121.240000
MedHouseVal,4.526000,3.585000,3.521000,3.413000,3.422000,2.697000,2.992000,2.414000,2.267000,2.611000,...,1.120000,1.072000,1.156000,0.983000,1.168000,0.781000,0.771000,0.923000,0.847000,0.894000

To get descriptive statistics:

In [30]:
df.describe()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
count,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000
mean,3.870671,28.639486,5.429000,1.096675,1425.476744,3.070655,35.631861,-119.569704,2.068558
std,1.899822,12.585558,2.474173,0.473911,1132.462122,10.386050,2.135952,2.003532,1.153956
min,0.499900,1.000000,0.846154,0.333333,3.000000,0.692308,32.540000,-124.350000,0.149990
25%,2.563400,18.000000,4.440716,1.006079,787.000000,2.429741,33.930000,-121.800000,1.196000
50%,3.534800,29.000000,5.229129,1.048780,1166.000000,2.818116,34.260000,-118.490000,1.797000
75%,4.743250,37.000000,6.052381,1.099526,1725.000000,3.282261,37.710000,-118.010000,2.647250
max,15.000100,52.000000,141.909091,34.066667,35682.000000,1243.333333,41.950000,-114.310000,5.000010

And other aggregations like `DataFrame.mean()` you may have seen in last section:

In [31]:
# Max over columns
df.max()

MedInc            15.000100
HouseAge          52.000000
AveRooms         141.909091
AveBedrms         34.066667
Population     35682.000000
AveOccup        1243.333333
Latitude          41.950000
Longitude       -114.310000
MedHouseVal        5.000010
dtype: float64

In [32]:
# numbber of unique values in each column
df.nunique() #distinctive values

MedInc         12928
HouseAge          52
AveRooms       19392
AveBedrms      14233
Population      3888
AveOccup       18841
Latitude         862
Longitude        844
MedHouseVal     3842
dtype: int64

In [33]:
# number of distinct values for column tax (distinct rows)
df.HouseAge.value_counts() # order based on appearance in the dataset

HouseAge
52.0    1273
36.0     862
35.0     824
16.0     771
17.0     698
34.0     689
26.0     619
33.0     615
18.0     570
25.0     566
32.0     565
37.0     537
15.0     512
19.0     502
27.0     488
24.0     478
30.0     476
28.0     471
20.0     465
29.0     461
31.0     458
23.0     448
21.0     446
14.0     412
22.0     399
38.0     394
39.0     369
42.0     368
44.0     356
43.0     353
40.0     304
13.0     302
41.0     296
45.0     294
10.0     264
11.0     254
46.0     245
5.0      244
12.0     238
8.0      206
9.0      205
47.0     198
4.0      191
48.0     177
7.0      175
6.0      160
50.0     136
49.0     134
3.0       62
2.0       58
51.0      48
1.0        4
Name: count, dtype: int64

In [34]:
# Pairwise correlation of columns
df.corr()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
MedInc,1.000000,-0.119034,0.326895,-0.062040,0.004834,0.018766,-0.079809,-0.015176,0.688075
HouseAge,-0.119034,1.000000,-0.153277,-0.077747,-0.296244,0.013191,0.011173,-0.108197,0.105623
AveRooms,0.326895,-0.153277,1.000000,0.847621,-0.072213,-0.004852,0.106389,-0.027540,0.151948
AveBedrms,-0.062040,-0.077747,0.847621,1.000000,-0.066197,-0.006181,0.069721,0.013344,-0.046701
Population,0.004834,-0.296244,-0.072213,-0.066197,1.000000,0.069863,-0.108785,0.099773,-0.024650
AveOccup,0.018766,0.013191,-0.004852,-0.006181,0.069863,1.000000,0.002366,0.002476,-0.023737
Latitude,-0.079809,0.011173,0.106389,0.069721,-0.108785,0.002366,1.000000,-0.924664,-0.144160
Longitude,-0.015176,-0.108197,-0.027540,0.013344,0.099773,0.002476,-0.924664,1.000000,-0.045967
MedHouseVal,0.688075,0.105623,0.151948,-0.046701,-0.024650,-0.023737,-0.144160,-0.045967,1.000000

#### Quiz

1. Go to Pandas [documentation](https://pandas.pydata.org/docs/reference/index.html), and find a `method` for `DataFrame` to calculate the variance of each variable.

## 3. Data Manipulation

### 3.1 Conditional Filtering

`DataFrame` support row-wise filtering using complex conditional logics.

For example, to show the average number of home occupants only in blocks where the population is greater than 1000:

In [40]:
df.loc[df.Population > 1000, "AveOccup"]

1        2.109842
6        2.128405
7        1.788253
8        2.026891
9        2.172269
           ...
20632    2.719481
20633    2.832461
20634    3.026163
20637    2.325635
20639    2.616981
Name: AveOccup, Length: 12483, dtype: float64

#### Quiz *

Find the **mean** of average occupancy for blocks satisfying these conditions:
- `Population` greater than 1000
- `HouseAge` equal to 5

In [42]:
df.loc[(df.Population > 1000) & (df.HouseAge == 5), "AveOccup"].mean()

3.421266941781164

### 3.2 Transformation

Data transformation is very important method in data analytics, and `Pandas` provides easy way to operate row-wise transformation.

#### 3.2.1 Row-wise transformation
For example, if we want to transform the Population values into logarithmic scale, we have at least two approaches:

- We can call `.transform()`on one of the columns to return a transformed `Series`.
- Use a `numpy` Ufunc to perform universial transformation

In [51]:
# Using .apply() to apply a function to a column
df.Population.transform(lambda x: np.log(x))

0        5.774552
1        7.783641
2        6.206576
3        6.324359
4        6.336826
           ...
20635    6.739337
20636    5.874931
20637    6.914731
20638    6.608001
20639    7.234898
Name: Population, Length: 20640, dtype: float64

In [52]:
# Or, using Ufucs to apply a function to a column
np.log(df.Population)

0        5.774552
1        7.783641
2        6.206576
3        6.324359
4        6.336826
           ...
20635    6.739337
20636    5.874931
20637    6.914731
20638    6.608001
20639    7.234898
Name: Population, Length: 20640, dtype: float64

### Quiz *

Calculate the mean (let's call it ${\bar X}$) and standard deviation (call it ${\sigma_X}$) of `Population`.

Then use `.transform` to perform a (z-)standarisation for `Population`:

$$x^{(i)}_{standarisation} = \frac{x^{(i)} - \bar X}{\sigma_X}$$

This transforms each `Population` value so that it now represents how many `Population` standard deviations away it is from the `Population` mean

In [46]:
df.Population.transform(lambda x: (x - x.mean())/x.std())

0       -0.974405
1        0.861418
2       -0.820757
3       -0.766010
4       -0.759828
           ...
20635   -0.512579
20636   -0.944382
20637   -0.369528
20638   -0.604415
20639   -0.033976
Name: Population, Length: 20640, dtype: float64

#### 3.2.2 Data Binning

Sometimes, binning a continuous variable into a discrete variable is very helpful to extract the key information (e.g., draw a dense bar chart to explore its distribution) and also save computations for further usage.

Let's bin the population variable into quintiles (5 different levels based on statistics)

In [37]:
popQuintiles = pd.qcut(df.Population, 5, labels = ['Very Low', 'Low', 'Medium', 'High', 'Very High'])
popQuintiles

0         Very Low
1        Very High
2         Very Low
3         Very Low
4         Very Low
           ...
20635          Low
20636     Very Low
20637          Low
20638          Low
20639         High
Name: Population, Length: 20640, dtype: category
Categories (5, object): ['Very Low' < 'Low' < 'Medium' < 'High' < 'Very High']

Now let's copy the dataframe and add these population quintiles as a new column to the copy.

Notice how we have used `.columns.get_loc` to place the new column next to the `Population` column.

In [39]:
df_copy = df.copy()
col_index = df.columns.get_loc("Population") + 1
df_copy.insert(loc = col_index, column = "Pop. Quintiles", value = popQuintiles)
df_copy

,MedInc,HouseAge,AveRooms,AveBedrms,Population,Pop. Quintiles,AveOccup,Latitude,Longitude,MedHouseVal
0,8.3252,41.0,6.984127,1.023810,322.0,Very Low,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,Very High,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,Very Low,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,Very Low,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,Very Low,2.181467,37.85,-122.25,3.422
...,...,...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,Low,2.560606,39.48,-121.09,0.781
20636,2.5568,18.0,6.114035,1.315789,356.0,Very Low,3.122807,39.49,-121.21,0.771
20637,1.7000,17.0,5.205543,1.120092,1007.0,Low,2.325635,39.43,-121.22,0.923
20638,1.8672,18.0,5.329513,1.171920,741.0,Low,2.123209,39.43,-121.32,0.847
20639,2.3886,16.0,5.254717,1.162264,1387.0,High,2.616981,39.37,-121.24,0.894

#### Quiz

1.

In [ ]:
df

### 3.3 Grouping for Aggregation, Transformation and Filtration

By “group by” we are referring to a process involving one or more of the following steps:

1. Splitting the data into groups based on some criteria

2. Applying a function to each group independently

3. Combining the results into a data structure

#### 3.3.1 GroupBy Aggregation

Let's group the data by House Age and then look at the average population in each of these groups

In [44]:
# Generate a GroupBy object
HouseAge_groups = df.groupby('HouseAge')
HouseAge_groups.Population.mean()

HouseAge
1.0      328.500000
2.0     2083.051724
3.0     3001.774194
4.0     2813.162304
5.0     2471.381148
6.0     2165.637500
7.0     2613.080000
8.0     2018.354369
9.0     1886.975610
10.0    1712.924242
11.0    1989.905512
12.0    2129.613445
13.0    1776.347682
14.0    1857.140777
15.0    1622.308594
16.0    1483.556420
17.0    1605.848138
18.0    1608.664912
19.0    1619.286853
20.0    1545.584946
21.0    1657.793722
22.0    1736.686717
23.0    1554.285714
24.0    1610.000000
25.0    1539.491166
26.0    1437.591276
27.0    1412.657787
28.0    1443.577495
29.0    1454.225597
30.0    1413.836134
31.0    1390.796943
32.0    1364.886726
33.0    1304.369106
34.0    1233.134978
35.0    1204.427184
36.0    1093.349188
37.0    1080.089385
38.0    1100.913706
39.0    1160.252033
40.0    1094.674342
41.0    1040.043919
42.0    1134.913043
43.0    1064.963173
44.0    1031.109551
45.0    1035.323129
46.0    1051.808163
47.0    1060.015152
48.0     970.926554
49.0     989.194030
50.0     998.977941
51.0     941.312500
52.0     934.271013
Name: Population, dtype: float64

How about we group our copied dataframe by both HouseAge and Pop. Quintiles?

In [47]:
occup_popq_groups = df_copy.groupby(['HouseAge', 'Pop. Quintiles'])
occup_popq_groups.Population.mean()

/var/folders/0k/xwb6rsgn75b4ybm10gqj07240000gn/T/ipykernel_18271/2584821384.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  occup_popq_groups = df_copy.groupby(['HouseAge', 'Pop. Quintiles'])

HouseAge  Pop. Quintiles
1.0       Very Low           147.333333
          Low                872.000000
          Medium                    NaN
          High                      NaN
          Very High                 NaN
                               ...
52.0      Very Low           448.047945
          Low                859.904348
          Medium            1155.128114
          High              1557.208861
          Very High         2466.372549
Name: Population, Length: 260, dtype: float64

### 3.4 Data Concatenation

Pandas offers multiple ways to concatenate multiple `DataFrames`, including simple concatenation like we have seen in Numpy, and also joining operation that you may know in SQL.

Let's start with three separated datasets of the Boston Housing Dataset.

In [ ]:
boston_housing_p1 = pd.read_csv("./datasets/BostonHousing_part1.csv", index_col= 0)
boston_housing_p1

In [ ]:
boston_housing_p2 = pd.read_csv("./datasets/BostonHousing_part2.csv", index_col= 0)
boston_housing_p2

In [ ]:
boston_housing_p3 = pd.read_csv("./datasets/BostonHousing_part3.csv", index_col= 0)
boston_housing_p3

#### 3.3.1 Concatenation with `pd.concat`

Let's concatenate the three separated datasets back to a complete Boston Housing Dataset:

In [ ]:
boston_housing_hstack = pd.concat([boston_housing_p1, boston_housing_p2], axis = 1)
boston_housing_hstack

In [ ]:
boston_housing_vstack = pd.concat([boston_housing_hstack, boston_housing_p3], axis = 0)
boston_housing_vstack

#### 3.3.2 Concatenation with `pd.merge()`

`pd.merge()` enables SQL style join types along specific columns. Let's start with two `DataFrame` storing students' scores for Python and Math.

In [ ]:
Python_df = pd.DataFrame(data = {'Name': ['Alice', 'Bob', 'Cathy', 'David'], 'Python': [80, 85, 90, 95]})
Python_df

In [ ]:
Math_df = pd.DataFrame(data = {'Name': ['Bob', 'Cathy', 'David', 'Edward'], 'Math': [85, 90, 95, 100]})
Math_df

To left join Python_df with Math_df:

In [ ]:
all_scores = pd.merge(Python_df, Math_df, on = 'Name', how = 'left')
all_scores

#### Quiz

1. What are expected results for `how = 'right'`, `how = 'outer` and `how = 'inner'`?

## 4. Missing Value Processing

- Assumption: the data you will be given is clean and tidy

- Reality: It is usually an utter mess

Before we go further, let's see how the computer save a missing value.

### 4.0 Type of Missing Value

#### 4.0.1 `None`: Pythonic Missing Data

In [ ]:
vals1 = np.array([1, None, 3, 4])
vals1

Try to run the following cell, what is expected?

In [ ]:
vals1.sum()

#### 4.0.2 `NaN`: Missing Numerical Data

In [ ]:
vals2 = np.array([1, np.nan, 3, 4]) 
vals2

Try to run the following cell, what is expected?

In [ ]:
vals2.sum()

### 4.1 Detecting null values

Pandas data structures have two useful methods for detecting null data: `isnull()` and `notnull()`. Either one will return a Boolean mask over the data.

Let's read the Boston Housing Dataset with missing values.

In [ ]:
df.head()

Use `DataFrame.isnull()` to detect missing values:

In [ ]:
df.isnull()

A concise way:

In [ ]:
df.isnull().sum()

### 4.2 Dropping or Filling?

In addition to the masking used before, there are the convenience methods, `dropna()` (which removes NA values) and `fillna()` (which fills in NA values):

Before we compare the two methods, let's generate a copy:

In [ ]:
df_copy = df.copy()

#### 4.2.1 Drop rows with missing values:

In [ ]:
df_copy.dropna(axis = 0, inplace = False)

#### 4.2.2 Fill null values with `DataFrame.fillna()`:

- by a fixed value (mean, median, ...)
- ffill: propagate last valid observation forward to next valid.
- bfill: use next valid observation to fill gap.

Fill column "CHAS" with `0`:

In [ ]:
df_copy.chas = df_copy.chas.fillna(value = 0)
df_copy.head()

Fill column "NOX" using `ffill` method:

In [ ]:
df_copy.nox = df_copy.nox.fillna(method = 'ffill')
df_copy.head()

#### Quiz

1. Fill column "LSTAT" with its median

2. Fill column "AGE" using backfill method

#### 4.2.3 Fill null values with `DataFrame.interpolate()`

Interpolation is a more adaptive method that can fill the missing value in a more "smart" way. However, this method is always much more computationally costly.

Fill column "MEDV" with "cubic" interpolation:

P.S. "cubic" interpolation assumes a cubic relationship between known data points. It uses a cubic polynomial to estimate values.

In [ ]:
df_copy.medv = df_copy.medv.interpolate(method = 'cubic')
df_copy.head()

Fill column "b" with "linear" interpolation:

P.S. "linear" interpolation assumes a linear relationship between known data points. It connects two adjacent points with a straight line and estimates values along that line.

In [ ]:
df_copy.b = df_copy.b.interpolate(method = 'linear')
df_copy.head()

#### Quiz

1. Fill column "crim" using any interpolation method and justify the reason.

#### 3.3.3 GroupBy Filtering*

GroupBy Filtering `groupby.filter()` can filter elements from groups that don’t satisfy a criterion.

Let's try to filter out the MEDV levels when the mean TAX in this level is less than 250.

In [ ]:
# You should see only "Very High" level left
df_copy.groupby('Pop. Quintiles').filter(lambda x: x.Pop..mean() < 250)
grouped_medv.filter(lambda x: x.tax.mean() < 250)

from sklearn import fetch_boston_housing

In [46]:
df.Population.transform(lambda x: (x - x.mean())/x.std())

0       -0.974405
1        0.861418
2       -0.820757
3       -0.766010
4       -0.759828
           ...
20635   -0.512579
20636   -0.944382
20637   -0.369528
20638   -0.604415
20639   -0.033976
Name: Population, Length: 20640, dtype: float64

In [54]:
from sklearn.datasets import load_boston

ImportError:
`load_boston` has been removed from scikit-learn since version 1.2.

The Boston housing prices dataset has an ethical problem: as
investigated in [1], the authors of this dataset engineered a
non-invertible variable "B" assuming that racial self-segregation had a
positive impact on house prices [2]. Furthermore the goal of the
research that led to the creation of this dataset was to study the
impact of air quality but it did not give adequate demonstration of the
validity of this assumption.

The scikit-learn maintainers therefore strongly discourage the use of
this dataset unless the purpose of the code is to study and educate
about ethical issues in data science and machine learning.

In this special case, you can fetch the dataset from the original
source::

    import pandas as pd
    import numpy as np

    data_url = "http://lib.stat.cmu.edu/datasets/boston"
    raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
    data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
    target = raw_df.values[1::2, 2]

Alternative datasets include the California housing dataset and the
Ames housing dataset. You can load the datasets as follows::

    from sklearn.datasets import fetch_california_housing
    housing = fetch_california_housing()

for the California housing dataset and::

    from sklearn.datasets import fetch_openml
    housing = fetch_openml(name="house_prices", as_frame=True)

for the Ames housing dataset.

[1] M Carlisle.
"Racist data destruction?"
<https://medium.com/@docintangible/racist-data-destruction-113e3eff54a8>

[2] Harrison Jr, David, and Daniel L. Rubinfeld.
"Hedonic housing prices and the demand for clean air."
Journal of environmental economics and management 5.1 (1978): 81-102.
<https://www.researchgate.net/publication/4974606_Hedonic_housing_prices_and_the_demand_for_clean_air>